# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
