# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0003_employees_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='country',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='employees',
            name='image_thumb',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='employees',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='employees',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
    ]
